import { i18n, type Locale, normalizeLocale } from './config';

interface ExperiencePoint {
  text: string;
  emphasis?: boolean;
}

interface ExperienceItem {
  title: string;
  badge: string;
  points: ExperiencePoint[];
}

interface ProjectItem {
  title: string;
  description: string;
  tech: string;
}

interface ResearchItem {
  title: string;
  description: string;
  tech: string;
}

export interface Dictionary {
  metadata: {
    title: string;
    description: string;
  };
  navbar: {
    navigation: string;
    social: string;
    language: string;
    sections: {
      landing: string;
      experience: string;
      skills: string;
      projects: string;
      research: string;
      contact: string;
    };
    socialLinks: {
      github: string;
      linkedin: string;
    };
    languageNames: Record<Locale, string>;
  };
  landing: {
    intro: string;
    words: {
      desktopLine1: string[];
      desktopLine2: string[];
      mobile: string[];
    };
    actions: {
      downloadCv: string;
      contactMe: string;
    };
  };
  experience: {
    title: string;
    items: ExperienceItem[];
  };
  skills: {
    title: string;
  };
  projects: {
    title: string;
    items: ProjectItem[];
  };
  research: {
    title: string;
    items: ResearchItem[];
  };
  contact: {
    title: string;
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    messageLabel: string;
    messagePlaceholder: string;
    submit: string;
  };
}

const dictionaries: Record<'en' | 'es' | 'pt', Dictionary> = {
  en: {
    metadata: {
      title: 'Portfolio Luis Sante',
      description: 'Welcome to my portfolio!',
    },
    navbar: {
      navigation: 'Navigation',
      social: 'Social',
      language: 'Language',
      sections: {
        landing: 'Landing Page',
        experience: 'Experience',
        skills: 'Skills',
        projects: 'Projects',
        research: 'Research Project',
        contact: 'Contact Me',
      },
      socialLinks: {
        github: 'GitHub',
        linkedin: 'LinkedIn',
      },
      languageNames: {
        en: 'EN',
        es: 'ES',
        pt: 'PT',
        fr: 'FR',
        de: 'DE',
        it: 'IT',
      },
    },
    landing: {
      intro: "Hello, I'm Luis Sante. A programmer passionate about Artificial Intelligence",
      words: {
        desktopLine1: ['Artificial', 'Intelligence'],
        desktopLine2: ['and', 'Machine', 'Learning'],
        mobile: ['AI', 'and', 'ML'],
      },
      actions: {
        downloadCv: 'Download CV',
        contactMe: 'Contact Me',
      },
    },
    experience: {
      title: 'Experience',
      items: [
        {
          title: 'Outlier AI',
          badge: 'Artificial Intelligence Training Engineer • Jun 2024 - Jun 10, 2024',
          points: [
            {
              text: 'I worked on a project called Flamingo MultiTurn, whose objective is to test a generative model using prompts. We compared two responses generated by the LLM model and evaluated which was better in several dimensions.',
            },
            {
              text: 'These evaluations allowed us to obtain better answers and generate new training data that contributed to refining and optimizing the LLM. This experience helped me develop advanced skills in language model analysis, data management, and collaborative work in a cutting-edge technological environment.',
            },
            {
              text: 'Language: Python, JavaScript, Java, TypeScript',
              emphasis: true,
            },
            {
              text: 'Frameworks: Vue.js, ReactJS',
              emphasis: true,
            },
          ],
        },
        {
          title: 'LexCom AI',
          badge: 'Tech Lead • Oct. 2023 - Jun. 2024',
          points: [
            {
              text: 'Led the development of an AI-based product profitability prediction system for an e-commerce platform, plus extra services such as text generators using the OpenAI API. The project covered backend and frontend development through cloud deployment.',
            },
            {
              text: 'Utilized data balancing techniques such as SMOTE during the training phase to enhance dataset accuracy and improve model performance.',
            },
            {
              text: 'Coordinated backend and frontend integration, ensuring a smooth and functional user experience.',
            },
            {
              text: 'Managed secure authentication with JWT and configured reverse proxies using Nginx Proxy Manager.',
            },
            {
              text: 'Containerized the application with Docker, facilitating deployment and maintenance.',
            },
            {
              text: 'Deployed the solution on Google Cloud Platform (Compute Engine).',
            },
            {
              text: 'Developed AI features using advanced machine learning techniques.',
            },
            {
              text: 'Built with: Python, TypeScript, Django REST framework, React, Vite, PostgreSQL, JWT, Docker, Compute Engine GCP, Nginx Proxy Manager',
              emphasis: true,
            },
            {
              text: 'Note: The project is private on GitHub, but I can provide access for review upon request.',
              emphasis: true,
            },
          ],
        },
      ],
    },
    skills: {
      title: 'Skills',
    },
    projects: {
      title: 'Projects',
      items: [
        {
          title: 'Fine-Tuning of LLaMA 2 with QLoRA Optimization',
          description:
            "Conducted fine-tuning of the 'NousResearch/Llama-2-7b-chat-hf' model using the 'mlabonne/guanaco-llama2-1k' dataset to create the customized 'llama-2-7b-miniguanaco' model. Implemented QLoRA with a 64-dimension LoRA attention layer and 4-bit precision to optimize model performance while maintaining resource efficiency. Configured and trained the model with advanced hyperparameters including cosine learning rate scheduling, gradient checkpointing, and paged_adamw_32bit optimization.",
          tech: 'Fine Tuning - Python - Hugging Face - PyTorch - LLaMA2 - QLoRA',
        },
        {
          title: 'Image Classification',
          description:
            'Developed a Convolutional Neural Network (CNN) model for image classification, achieving an accuracy of 85.72% on the test set. Preprocessed image data using data augmentation and normalization to improve model generalization. Implemented the model using TensorFlow/Keras and optimized its performance through hyperparameter tuning.',
          tech: 'Python - TensorFlow - Convolutional Neural Network - Data Augmentation',
        },
        {
          title: 'AI for E-Commerce Profitability Insights',
          description:
            'Led the development of an AI-based product profitability prediction system for an e-commerce platform, plus extra services such as text generation with OpenAI API. The project covered backend and frontend development through cloud deployment, and used SMOTE to improve training quality.',
          tech: 'Python - Random Forest - SMOTE - Scrapy',
        },
        {
          title: 'Stroke Prediction',
          description:
            'Developed a machine learning model to predict stroke likelihood using medical data, achieving 91.12% validation accuracy. Applied feature engineering and model selection strategies including Random Forest and XGBoost, and used SMOTE to handle class imbalance.',
          tech: 'Python - Random Forest - XGBoost - Feature Engineering',
        },
      ],
    },
    research: {
      title: 'Research Projects',
      items: [
        {
          title: 'Topic Modelling for Functionality Detection',
          description:
            'Topic modeling to find functionalities within user reviews of a Google Play Store app using unsupervised algorithms and sentence embeddings with Transformers. This research contributed to better understanding user needs and app development priorities.',
          tech: 'Natural Language Processing - Topic Modelling - Python - Transformers - Clustering - Embeddings',
        },
      ],
    },
    contact: {
      title: 'Contact me',
      nameLabel: 'Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email',
      emailPlaceholder: 'email@gmail.com',
      messageLabel: 'Message',
      messagePlaceholder: 'Type your message here.',
      submit: 'Submit',
    },
  },
  es: {
    metadata: {
      title: 'Portafolio Luis Sante',
      description: 'Bienvenido a mi portafolio.',
    },
    navbar: {
      navigation: 'Navegación',
      social: 'Redes',
      language: 'Idioma',
      sections: {
        landing: 'Inicio',
        experience: 'Experiencia',
        skills: 'Habilidades',
        projects: 'Proyectos',
        research: 'Investigación',
        contact: 'Contáctame',
      },
      socialLinks: {
        github: 'GitHub',
        linkedin: 'LinkedIn',
      },
      languageNames: {
        en: 'EN',
        es: 'ES',
        pt: 'PT',
        fr: 'FR',
        de: 'DE',
        it: 'IT',
      },
    },
    landing: {
      intro: 'Hola, soy Luis Sante. Programador apasionado por la Inteligencia Artificial',
      words: {
        desktopLine1: ['Inteligencia', 'Artificial'],
        desktopLine2: ['y', 'Aprendizaje', 'Automático'],
        mobile: ['IA', 'y', 'ML'],
      },
      actions: {
        downloadCv: 'Descargar CV',
        contactMe: 'Contáctame',
      },
    },
    experience: {
      title: 'Experiencia',
      items: [
        {
          title: 'Outlier AI',
          badge: 'Ingeniero de Entrenamiento en IA • Jun 2024 - Jun 10, 2024',
          points: [
            {
              text: 'Trabajé en un proyecto llamado Flamingo MultiTurn, cuyo objetivo fue evaluar un modelo generativo mediante prompts. Comparamos dos respuestas generadas por el modelo LLM y evaluamos cuál era mejor en distintas dimensiones.',
            },
            {
              text: 'Estas evaluaciones permitieron obtener mejores respuestas y generar nuevos datos de entrenamiento que ayudaron a refinar y optimizar el LLM. Esta experiencia fortaleció mis habilidades en análisis de modelos de lenguaje, gestión de datos y trabajo colaborativo en un entorno tecnológico de vanguardia.',
            },
            {
              text: 'Lenguajes: Python, JavaScript, Java, TypeScript',
              emphasis: true,
            },
            {
              text: 'Frameworks: Vue.js, ReactJS',
              emphasis: true,
            },
          ],
        },
        {
          title: 'LexCom AI',
          badge: 'Tech Lead • Oct. 2023 - Jun. 2024',
          points: [
            {
              text: 'Lideré el desarrollo de un sistema de predicción de rentabilidad de productos basado en IA para un e-commerce, además de servicios adicionales como generadores de texto con la API de OpenAI. El proyecto abarcó backend, frontend y despliegue en la nube.',
            },
            {
              text: 'Apliqué técnicas de balanceo de datos como SMOTE durante el entrenamiento para mejorar la precisión del dataset y el rendimiento del modelo.',
            },
            {
              text: 'Coordiné la integración entre backend y frontend, asegurando una experiencia de usuario fluida y funcional.',
            },
            {
              text: 'Gestioné la autenticación segura con JWT y la configuración de proxies reversos usando Nginx Proxy Manager.',
            },
            {
              text: 'Realicé la containerización de la aplicación con Docker, facilitando despliegue y mantenimiento.',
            },
            {
              text: 'Desplegué la solución en Google Cloud Platform (Compute Engine).',
            },
            {
              text: 'Desarrollé funcionalidades de IA con técnicas avanzadas de machine learning.',
            },
            {
              text: 'Construido con: Python, TypeScript, Django REST framework, React, Vite, PostgreSQL, JWT, Docker, Compute Engine GCP, Nginx Proxy Manager',
              emphasis: true,
            },
            {
              text: 'Nota: El proyecto es privado en GitHub, pero puedo dar acceso para revisión si lo solicitas.',
              emphasis: true,
            },
          ],
        },
      ],
    },
    skills: {
      title: 'Habilidades',
    },
    projects: {
      title: 'Proyectos',
      items: [
        {
          title: 'Fine-Tuning de LLaMA 2 con optimización QLoRA',
          description:
            "Realicé fine-tuning del modelo 'NousResearch/Llama-2-7b-chat-hf' usando el dataset 'mlabonne/guanaco-llama2-1k' para crear el modelo personalizado 'llama-2-7b-miniguanaco'. Implementé QLoRA con una capa de atención LoRA de 64 dimensiones y precisión de 4 bits para optimizar el rendimiento con eficiencia de recursos. Configuré y entrené el modelo con hiperparámetros avanzados como cosine learning rate, gradient checkpointing y paged_adamw_32bit.",
          tech: 'Fine Tuning - Python - Hugging Face - PyTorch - LLaMA2 - QLoRA',
        },
        {
          title: 'Clasificación de Imágenes',
          description:
            'Desarrollé un modelo de red neuronal convolucional (CNN) para clasificación de imágenes, logrando 85.72% de precisión en el conjunto de prueba. Preprocesé datos con augmentación y normalización para mejorar la generalización. Implementé el modelo con TensorFlow/Keras y lo optimicé con ajuste de hiperparámetros.',
          tech: 'Python - TensorFlow - Convolutional Neural Network - Data Augmentation',
        },
        {
          title: 'IA para rentabilidad en E-Commerce',
          description:
            'Lideré el desarrollo de un sistema de predicción de rentabilidad de productos con IA para una plataforma de e-commerce, junto con servicios de generación de texto usando la API de OpenAI. El proyecto cubrió backend, frontend y despliegue en la nube, usando SMOTE para mejorar la calidad del entrenamiento.',
          tech: 'Python - Random Forest - SMOTE - Scrapy',
        },
        {
          title: 'Predicción de Ictus',
          description:
            'Desarrollé un modelo de machine learning para predecir probabilidad de ictus con datos médicos, alcanzando 91.12% de precisión en validación. Apliqué ingeniería de características y selección de modelos con Random Forest y XGBoost, además de SMOTE para tratar el desbalance de clases.',
          tech: 'Python - Random Forest - XGBoost - Feature Engineering',
        },
      ],
    },
    research: {
      title: 'Proyectos de Investigación',
      items: [
        {
          title: 'Modelado de Tópicos para detección de funcionalidades',
          description:
            'Modelado de tópicos para identificar funcionalidades dentro de reseñas de usuarios de una app en Google Play Store mediante algoritmos no supervisados y embeddings de oraciones con Transformers. Esta investigación aportó una mejor comprensión de las necesidades del usuario y prioridades de desarrollo.',
          tech: 'Procesamiento de Lenguaje Natural - Topic Modelling - Python - Transformers - Clustering - Embeddings',
        },
      ],
    },
    contact: {
      title: 'Contáctame',
      nameLabel: 'Nombre',
      namePlaceholder: 'Tu nombre',
      emailLabel: 'Correo',
      emailPlaceholder: 'correo@gmail.com',
      messageLabel: 'Mensaje',
      messagePlaceholder: 'Escribe tu mensaje aquí.',
      submit: 'Enviar',
    },
  },
  pt: {
    metadata: {
      title: 'Portfólio Luis Sante',
      description: 'Bem-vindo ao meu portfólio.',
    },
    navbar: {
      navigation: 'Navegação',
      social: 'Redes',
      language: 'Idioma',
      sections: {
        landing: 'Início',
        experience: 'Experiência',
        skills: 'Habilidades',
        projects: 'Projetos',
        research: 'Pesquisa',
        contact: 'Contato',
      },
      socialLinks: {
        github: 'GitHub',
        linkedin: 'LinkedIn',
      },
      languageNames: {
        en: 'EN',
        es: 'ES',
        pt: 'PT',
        fr: 'FR',
        de: 'DE',
        it: 'IT',
      },
    },
    landing: {
      intro: 'Olá, eu sou Luis Sante. Programador apaixonado por Inteligência Artificial',
      words: {
        desktopLine1: ['Inteligência', 'Artificial'],
        desktopLine2: ['e', 'Machine', 'Learning'],
        mobile: ['IA', 'e', 'ML'],
      },
      actions: {
        downloadCv: 'Baixar CV',
        contactMe: 'Fale comigo',
      },
    },
    experience: {
      title: 'Experiência',
      items: [
        {
          title: 'Outlier AI',
          badge: 'Engenheiro de Treinamento em IA • Jun 2024 - Jun 10, 2024',
          points: [
            {
              text: 'Trabalhei em um projeto chamado Flamingo MultiTurn, cujo objetivo era avaliar um modelo generativo usando prompts. Comparamos duas respostas geradas pelo modelo LLM e avaliamos qual era melhor em diferentes dimensões.',
            },
            {
              text: 'Essas avaliações permitiram obter respostas melhores e gerar novos dados de treinamento que contribuíram para refinar e otimizar o LLM. Essa experiência fortaleceu minhas habilidades em análise de modelos de linguagem, gestão de dados e trabalho colaborativo em um ambiente tecnológico de ponta.',
            },
            {
              text: 'Linguagens: Python, JavaScript, Java, TypeScript',
              emphasis: true,
            },
            {
              text: 'Frameworks: Vue.js, ReactJS',
              emphasis: true,
            },
          ],
        },
        {
          title: 'LexCom AI',
          badge: 'Tech Lead • Out. 2023 - Jun. 2024',
          points: [
            {
              text: 'Liderei o desenvolvimento de um sistema de previsão de lucratividade de produtos baseado em IA para uma plataforma de e-commerce, além de serviços extras como geração de texto com a API da OpenAI. O projeto cobriu backend, frontend e deploy em nuvem.',
            },
            {
              text: 'Utilizei técnicas de balanceamento de dados, como SMOTE, durante o treinamento para melhorar a acurácia do dataset e o desempenho do modelo.',
            },
            {
              text: 'Coordenei a integração entre backend e frontend, garantindo uma experiência de usuário fluida e funcional.',
            },
            {
              text: 'Gerenciei autenticação segura com JWT e configuração de proxies reversos com Nginx Proxy Manager.',
            },
            {
              text: 'Realizei a containerização da aplicação com Docker, facilitando deploy e manutenção.',
            },
            {
              text: 'Fiz o deploy da solução no Google Cloud Platform (Compute Engine).',
            },
            {
              text: 'Desenvolvi funcionalidades de IA com técnicas avançadas de machine learning.',
            },
            {
              text: 'Construído com: Python, TypeScript, Django REST framework, React, Vite, PostgreSQL, JWT, Docker, Compute Engine GCP, Nginx Proxy Manager',
              emphasis: true,
            },
            {
              text: 'Nota: O projeto é privado no GitHub, mas posso fornecer acesso para revisão mediante solicitação.',
              emphasis: true,
            },
          ],
        },
      ],
    },
    skills: {
      title: 'Habilidades',
    },
    projects: {
      title: 'Projetos',
      items: [
        {
          title: 'Fine-Tuning do LLaMA 2 com otimização QLoRA',
          description:
            "Realizei fine-tuning do modelo 'NousResearch/Llama-2-7b-chat-hf' usando o dataset 'mlabonne/guanaco-llama2-1k' para criar o modelo personalizado 'llama-2-7b-miniguanaco'. Implementei QLoRA com camada de atenção LoRA de 64 dimensões e precisão de 4 bits para otimizar desempenho com eficiência de recursos. Configurei e treinei o modelo com hiperparâmetros avançados como cosine learning rate, gradient checkpointing e paged_adamw_32bit.",
          tech: 'Fine Tuning - Python - Hugging Face - PyTorch - LLaMA2 - QLoRA',
        },
        {
          title: 'Classificação de Imagens',
          description:
            'Desenvolvi um modelo de rede neural convolucional (CNN) para classificação de imagens, alcançando 85,72% de acurácia no conjunto de teste. Fiz pré-processamento com data augmentation e normalização para melhorar generalização. O modelo foi implementado com TensorFlow/Keras e otimizado com ajuste de hiperparâmetros.',
          tech: 'Python - TensorFlow - Convolutional Neural Network - Data Augmentation',
        },
        {
          title: 'IA para lucratividade em E-Commerce',
          description:
            'Liderei o desenvolvimento de um sistema de previsão de lucratividade de produtos com IA para e-commerce, junto com serviços de geração de texto usando a API da OpenAI. O projeto cobriu backend, frontend e deploy em nuvem, usando SMOTE para melhorar a qualidade do treinamento.',
          tech: 'Python - Random Forest - SMOTE - Scrapy',
        },
        {
          title: 'Predição de AVC',
          description:
            'Desenvolvi um modelo de machine learning para prever probabilidade de AVC com dados médicos, alcançando 91,12% de acurácia em validação. Apliquei engenharia de atributos e seleção de modelos com Random Forest e XGBoost, além de SMOTE para lidar com desbalanceamento de classes.',
          tech: 'Python - Random Forest - XGBoost - Feature Engineering',
        },
      ],
    },
    research: {
      title: 'Projetos de Pesquisa',
      items: [
        {
          title: 'Modelagem de Tópicos para detecção de funcionalidades',
          description:
            'Modelagem de tópicos para identificar funcionalidades em reviews de usuários de um app da Google Play Store usando algoritmos não supervisionados e embeddings de sentenças com Transformers. Essa pesquisa contribuiu para melhor entendimento das necessidades dos usuários e prioridades de desenvolvimento.',
          tech: 'Processamento de Linguagem Natural - Topic Modelling - Python - Transformers - Clustering - Embeddings',
        },
      ],
    },
    contact: {
      title: 'Contato',
      nameLabel: 'Nome',
      namePlaceholder: 'Seu nome',
      emailLabel: 'Email',
      emailPlaceholder: 'email@gmail.com',
      messageLabel: 'Mensagem',
      messagePlaceholder: 'Digite sua mensagem aqui.',
      submit: 'Enviar',
    },
  },
};

export function getDictionary(locale: string): Dictionary {
  const normalizedLocale = normalizeLocale(locale);
  const localeFallbackMap: Record<Locale, keyof typeof dictionaries> = {
    en: 'en',
    es: 'es',
    pt: 'pt',
    fr: 'en',
    de: 'en',
    it: 'en',
  };

  const dictionaryLocale = localeFallbackMap[normalizedLocale] ?? i18n.defaultLocale;
  return dictionaries[dictionaryLocale];
}
